(define (problem V3Problem) (:domain Redflix)

(:objects m1 m2 m3 m4 m5 - media
d0 d1 d2 d3 d4 - day )

(:init
    (antecedent m3 m2)
    (antecedent m1 m2)
    (watched m5)
    (= (dayNum d0) 0)
    (= (dayNum d1) 1)
    (= (dayNum d2) 2)
    (= (dayNum d3) 3)
    (= (dayNum d4) 4)
    (= (dayMinutesCount d0) 0)
    (= (dayMinutesCount d1) 1)
    (= (dayMinutesCount d2) 2)
    (= (dayMinutesCount d3) 3)
    (= (dayMinutesCount d4) 4)
    (= (dayAssignmentCount d0) 0)
    (= (dayAssignmentCount d1) 1)
    (= (dayAssignmentCount d2) 2)
    (= (dayAssignmentCount d3) 3)
    (= (dayAssignmentCount d4) 4)
    (= (mediaDuration m1) 53)
    (= (mediaDuration m2) 100)
    (= (mediaDuration m3) 94)
    (= (mediaDuration m4) 33)
    (= (mediaDuration m5) 37)
    (= (firstDayParallelAssignment m1) 1000)
    (= (firstDayParallelAssignment m2) 1000)
    (= (firstDayParallelAssignment m3) 1000)
    (= (firstDayParallelAssignment m4) 1000)
    (= (firstDayParallelAssignment m5) 1000)
)

(:goal (and
    (forall (?x - media) (imply (wantToWatch ?x) (mediaAsigned ?x)))
    (forall (?x - media) (forall (?y - media) (imply (and (wantToWatch ?x) (or (parallel ?x ?y) (parallel ?y ?x)) (not (watched ?y))  ) (mediaAsigned ?y)) ) )
))

)